# Generated by Django 4.1.7 on 2023-02-23 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubmittedSoftware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('developer', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('tags', models.BooleanField(default=False)),
                ('similar', models.CharField(max_length=25)),
                ('os', models.CharField(max_length=25)),
                ('image', models.URLField()),
            ],
        ),
    ]
