# Generated by Django 4.1.7 on 2023-04-20 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoftwareSubmissionPage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedsoftware',
            name='tag_test',
            field=models.BooleanField(default=False),
        ),
    ]
