# Generated by Django 4.1.7 on 2023-04-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoftwareSubmissionPage', '0002_submittedsoftware_tag_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submittedsoftware',
            name='tag_test',
        ),
        migrations.AddField(
            model_name='submittedsoftware',
            name='downloadLink',
            field=models.URLField(default='NO-URL'),
        ),
    ]
