# Generated by Django 4.1.7 on 2023-03-13 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoftwareSubmissionPage', '0002_rename_tags_submittedsoftware_os_mac_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittedsoftware',
            name='image',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
