# Generated by Django 4.1.7 on 2023-04-20 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SoftwareSubmissionPage', '0003_remove_submittedsoftware_tag_test_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submittedsoftware',
            name='downloadLink',
        ),
    ]
