# Generated by Django 4.1.7 on 2023-02-23 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoftwareSubmissionPage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submittedsoftware',
            old_name='tags',
            new_name='os_MAC',
        ),
        migrations.RemoveField(
            model_name='submittedsoftware',
            name='os',
        ),
        migrations.RemoveField(
            model_name='submittedsoftware',
            name='similar',
        ),
        migrations.AddField(
            model_name='submittedsoftware',
            name='os_NIX',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submittedsoftware',
            name='os_WIN',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submittedsoftware',
            name='tag_AntiVirus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submittedsoftware',
            name='tag_AudioEditor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submittedsoftware',
            name='tag_CodeEditor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submittedsoftware',
            name='tag_Communication',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submittedsoftware',
            name='tag_DiskBurner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submittedsoftware',
            name='tag_FileShare',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submittedsoftware',
            name='tag_GraphicsEditor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submittedsoftware',
            name='tag_Multimedia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submittedsoftware',
            name='tag_Other',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submittedsoftware',
            name='tag_SpreadSheet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submittedsoftware',
            name='tag_WordProcesser',
            field=models.BooleanField(default=False),
        ),
    ]
