# Generated by Django 4.1.7 on 2023-03-21 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_processor', models.CharField(max_length=100)),
                ('spreadsheet_editor', models.CharField(max_length=100)),
                ('file_sharing', models.CharField(max_length=100)),
                ('audio_editing', models.CharField(max_length=100)),
                ('graphical_editing', models.CharField(max_length=100)),
                ('antivirus', models.CharField(max_length=100)),
                ('communication', models.CharField(max_length=100)),
                ('disk_burning_software', models.CharField(max_length=100)),
                ('multimedia', models.CharField(max_length=100)),
                ('code_editor', models.CharField(max_length=100)),
                ('other', models.CharField(max_length=100)),
            ],
        ),
    ]
